### ISSUE TITLE
Request for a Installation Guide

### ISSUE THREAD

**Issue by stormerxd** [ddlsmurf/libfprint-CS9711#5]
I have a Chipsailing Fingerprint sensor that I want to make work in linux. I'm using Fedora previously was using Kali, but when I got to compile with Meson, some dependency would always be missing. Please give an elaborate installation guide.
![Screenshot From 2024-12-26 03-04-18](https://github.com/user-attachments/assets/30b4820e-0747-4975-be68-5bbe5e8561f1)

**Comment by ericlinagora** [comment]
I don't use Fedora, nor most package managers. There is some help in the original issue here: https://gitlab.freedesktop.org/libfprint/libfprint/-/issues/610#note_2357409 . If you write one, an elaborate installation guide would be a welcome contribution. My instructions for nixos are fine.

**Comment by stormerxd** [comment]
I went through the orginal and thanks to @Ziomal12, who had posted his own made rpm for the chipsailing libprint. This is how i got my Chipsailing Fingerprint to work on Fedora 41:
Step 1: Uninstall Default Fprint
```
sudo dnf remove fprintd
sudo dnf autoremove
```
(This command will clean up any dependencies that were installed with fprintd but are no longer required by other packages.)
Step 2: Download Ziomal's rpm for Fedora 41 and Fedora 40
https://github.com/Ziomal12/libfprint-CS9711/releases/tag/0.0.1
Step 3: Install it
Step 4: Now install fprintd 
`sudo dnf install fprintd && fprintd-pam`
Step 5: Reboot your system
Step 6: Edit the file fprintd.service
`sudo nano /usr/lib/systemd/system/fprintd.service`
Step 7: Add this to the end of the file
[Install] 
WantedBy=multi-user.target
Step 8: Save the file and run `systemctl restart fprintd.service`
Step 9: Enable fprintd with `systemctl enable fprintd.service`
Step 10: Enroll your fingerprint by `fprintd-enroll`
Now you'll be asked to enter your password, if all the steps are followed properly, if not  
`Impossible to enroll: GDBus.Error:net.reactivated.Fprint.Error.NoSuchDevice: No devices available`
this will appear
Step 11: Authenticate PAM for your fingerprint with 
`sudo authselect enable-feature with-fingerprint` 
`sudo authselect apply-changes`

**Comment by Ziomal12** [comment]
@stormerxd Right now I'm using Silverblue so I'm not sure how much of a difference it makes but I'm able to install the .rpm with `rpm-ostree override replace package-name` and after a reboot it's working. Now, on Workstation, it might be easier to just install with `sudo dnf swap libfprint libfprint-1.94.6-0.0.1.f42.x86_64.rpm` (I've prepared F42 build too but I'm gonna rebuild it after F42 comes out officially). I've tested it in toolbox however I'm not able to spin up VM with USB pass-through to test that properly.

When my workloads decreases I'm gonna look into either creating github action to automatically create packages for new releases or spinning up copr repo (less likely) along side with testing and adding more thorough instructions to README.

**Comment by stormerxd** [comment]
> [@stormerxd](https://github.com/stormerxd) Right now I'm using Silverblue so I'm not sure how much of a difference it makes but I'm able to install the .rpm with `rpm-ostree override replace package-name` and after a reboot it's working. Now, on Workstation, it might be easier to just install with `sudo dnf swap libfprint libfprint-1.94.6-0.0.1.f42.x86_64.rpm` (I've prepared F42 build too but I'm gonna rebuild it after F42 comes out officially). I've tested it in toolbox however I'm not able to spin up VM with USB pass-through to test that properly.
> 
> When my workloads decreases I'm gonna look into either creating github action to automatically create packages for new releases or spinning up copr repo (less likely) along side with testing and adding more thorough instructions to README.

@Ziomal12 I'm trying out SilverBlue today in the flavour of Bazzite, Can you tell me how you got it working in SilverBlue? wanted to try it out myself.

**Comment by HarisHashim** [comment]
> I went through the orginal and thanks to [@Ziomal12](https://github.com/Ziomal12), who had posted his own made rpm for the chipsailing libprint. This is how i got my Chipsailing Fingerprint to work on Fedora 41: Step 1: Uninstall Default Fprint
> 
> ```
> sudo dnf remove fprintd
> sudo dnf autoremove
> ```
> 
> (This command will clean up any dependencies that were installed with fprintd but are no longer required by other packages.) Step 2: Download Ziomal's rpm for Fedora 41 and Fedora 40 https://github.com/Ziomal12/libfprint-CS9711/releases/tag/0.0.1 Step 3: Install it Step 4: Now install fprintd `sudo dnf install fprintd && fprintd-pam` Step 5: Reboot your system Step 6: Edit the file fprintd.service `sudo nano /usr/lib/systemd/system/fprintd.service` Step 7: Add this to the end of the file [Install] WantedBy=multi-user.target Step 8: Save the file and run `systemctl restart fprintd.service` Step 9: Enable fprintd with `systemctl enable fprintd.service` Step 10: Enroll your fingerprint by `fprintd-enroll` Now you'll be asked to enter your password, if all the steps are followed properly, if not   `Impossible to enroll: GDBus.Error:net.reactivated.Fprint.Error.NoSuchDevice: No devices available` this will appear Step 11: Authenticate PAM for your fingerprint with  `sudo authselect enable-feature with-fingerprint` `sudo authselect apply-changes`

I can confirm that this step using Ziomal's rpm for Fedora 42 is working. Step 4 just need to change to `sudo dnf install fprintd && sudo dnf install fprintd-pam`  .

Done this using Fedora 42 on VirtualBox. The OS itself on VBox is very PITA and buggy! But CHIPSAILING 0236 is working fantastic.

**Comment by stormerxd** [comment]
Updated Guide for Fedora 42, tested by @HarisHashim 

Step 1: Uninstall Default Fprint
```
sudo dnf remove fprintd
sudo dnf autoremove
```
(This command will clean up any dependencies that were installed with fprintd but are no longer required by other packages.)
Step 2: Download Ziomal's rpm for Fedora 42
https://github.com/Ziomal12/libfprint-CS9711/releases/tag/0.0.1
Step 3: Install it
Step 4: Now install fprintd

`sudo dnf install fprintd && sudo dnf install fprintd-pam`
(Thanks to @HarisHashim `)`
Step 5: Reboot your system
Step 6: Edit the file fprintd.service
sudo nano /usr/lib/systemd/system/fprintd.service
Step 7: Add this to the end of the file
[Install]
WantedBy=multi-user.target
Step 8: Save the file and run 
`systemctl restart fprintd.service`
Step 9: Enable fprintd with 
`systemctl enable fprintd.service`
Step 10: Enroll your fingerprint by 
`fprintd-enroll`
Now you'll be asked to enter your password, if all the steps are followed properly, if not  
`Impossible to enroll: GDBus.Error:net.reactivated.Fprint.Error.NoSuchDevice: No devices available`
this will appear
Step 11: Authenticate PAM for your fingerprint with 
```
sudo authselect enable-feature with-fingerprint
sudo authselect apply-changes
```
